[package]
name = "max_values"
version = "1.0.0"
authors = ["Ihar Siulzhyn"]
description = "Struct and iterator extension trait for getting max values out of given"
edition = "2021"

[dependencies]
arrayvec = "^0.7"
